"""Create the schema-shaped R2 record from the completed independent review."""
import json
from datetime import datetime, timezone
from pathlib import Path

root = Path('D:/Codex Projects/ai-engineering-template')
p = '.ai/plans/current/PLAN-001/'
stem = p + 'reviews/TASK-006-a3-c3-R2'
identity = stem + '-identity.txt'
probes = stem + '-probes-linux311.txt'
declared = stem + '-declared.txt'
report = stem + '.md'
rows = [
    ('R2-01', 'LocalCommandRunner records observed process facts through the frozen port. Configuration, authorization inputs, validation evaluation, Git/state/worktree services and runtime wiring retain their declared owners.', [report, probes, p + 'tasks/current/TASK-007.json', p + 'tasks/current/TASK-018.json']),
    ('R2-02', 'ADR-001 through ADR-005 retain flat Python3.11+, local offline JSON contracts, independent task ownership, exact higher-capability fresh reviews and injected ports. Native submission provenance and retained cumulative recovery exceptions are explicit; no provider-effective identity is inferred.', [report, identity, p + 'evidence/effort-provenance-clarification.md', p + 'evidence/recovery/TASK-006-a2-coordinator-decision.md']),
    ('R2-03', 'Accepted002/004/038 commits are ancestors of the exact base; their owned source and handoff bytes match their accepted candidates. Real DTO, offline registry and immutable saved-settings interoperability passes independent probes.', [identity, probes, p + 'evidence/implementation/TASK-002.md', p + 'evidence/implementation/TASK-004.md', p + 'evidence/implementation/TASK-038.md']),
    ('R2-04', 'execute(CommandRequest)->CommandEvidence, runtime Protocol compatibility and explicit submodule imports remain unchanged. All six independent Linux imports resolve candidate src; literal repeated/significant argv and project/worktree/control cwd with no plan round-trip through actual children.', [report, probes, '.ai/shared/architecture/service-contracts.md']),
    ('R2-05', 'No API or version change. Actual exit9 and Git exit128 remain exited facts. Hydrated saved sandbox and explicit deny-all permissions refuse launch; partial log persistence becomes unknown/internal_error with null exit and only the genuinely stored stdout reference.', [probes, declared]),
    ('R2-06', 'No database, schema or migration change. Independent results validate against every exact closed v1 evidence field. Redacted combined bytes respect their budget and content refs verify after relocation; missing stderr is not fabricated on second-write failure.', [identity, probes, 'schemas/v1/command-evidence.schema.json']),
    ('R2-07', 'The raw base-to-head diff contains only commands.py, its isolated test leaf and owned plan-local handoff. Flat typed modules, accepted domain/error names, explicit imports and portable content refs follow current conventions.', [identity, report, '.ai/shared/architecture/python.md']),
    ('R2-08', 'No duplicate Git policy, operation journal, worktree lifecycle, success-rule evaluator or CLI wiring. Independent real zero-test execution stays exited-zero evidence while the accepted ValidationCheck rejects a claimed nonzero-count pass; later TASK-007/009/011/018/034 implementations remain unclaimed.', [probes, report, p + 'tasks/current/TASK-018.json']),
    ('R2-09', 'Host-local log/cancellation/tree collaborators add no competing portable DTO. Retained process identity and bounded frozen capture preserve explicit unknown when tree containment, EOF or durable storage cannot be proved; worktree scope is not represented as a sandbox.', [report, declared, probes, p + 'reviews/TASK-006-a3-c3-R1-linux-phase.txt']),
    ('R2-10', 'The exact terminal patch replaces only an incidental inherited-cancellation duration floor with present monotonic ordering and nonnegative bounded response. Real timeout floor, startup/elapsed/watchdog bounds, native phases, unconditional identity cleanup and later status/EOF/schema checks remain unchanged. Own declared suite passes all four phases; R1 independently proves final Linux schema checks and failure-only watchdog/readiness controls.', [identity, declared, p + 'reviews/TASK-006-a3-c3-R1-linux-phase.txt', p + 'reviews/TASK-006-a3-c3-R1-probes.txt', p + 'evidence/recovery/TASK-006-a2-recovery-assessment.md']),
    ('R2-11', 'Current handoff accurately separates a3 results from retained a1/a2 failures and malformed diagnostic setup, describes conservative containment/capture/storage limits, saved settings and downstream ownership, and requires fresh same-candidate reviews. This report records only executed independent validation and explicit provenance limitations.', [report, p + 'evidence/implementation/TASK-006.md', p + 'evidence/recovery/TASK-006-a3-harness-clarification.md']),
    ('R2-12', 'Approved r4 graph and all39-task structural digest, accepted dependencies, original scope and acceptance mapping remain valid. Exact R1 passes the same fingerprint; all14 context/four validation hashes and16 coordinator phase cleanups verify. No wider repair, shared contract change or replan is required; terminal future-failure pause and cumulative lineage remain intact.', [identity, stem + '-foundation.txt', report, p + 'reviews/TASK-006-a3-c3-R1.json', p + 'reviews/r4-isolation-review.json']),
]
record = dict(schema_version='1.0', kind='review-result', id='TASK-006-a3-c3-R2', stage='consistency', request_id='REVIEW-REQUEST-PLAN-001-TASK-006-a3-c3-R2', task_id='TASK-006', plan_id='PLAN-001', candidate_ref=p + 'reviews/candidates/CANDIDATE-TASK-006-a3-b41b37ac6b15.json', candidate_fingerprint='3df5453edcaf80c6237f35c5ca1c5adb81adfb9682cae3af95e25091d2435e80', verdict='pass', reviewer=dict(profile='review_high', provider='OpenAI', model_id='gpt-6-astra', capability_rank=4, invocation_id='call_GbgJkuZJORydnqcmQ4L3Qc4B'), independent_session_id='/root/review_006_c3_r2', implementation_session_id='/root/implement_006_a3', review_1_ref=p + 'reviews/TASK-006-a3-c3-R1.json', checklist_version='PLAN-001-v1', checks=[dict(id=key, status='pass', rationale=rationale, evidence=evidence) for key, rationale, evidence in rows], findings=[], created_at=datetime.now(timezone.utc).isoformat())
(root / (stem + '.json')).write_text(json.dumps(record, indent=2) + '\n', encoding='utf-8')
print('Wrote all12 consistency checks and exact same-candidate R1 reference.')
